version: "3.8"

services:
  mysql:
    build: ./db
    #Go to the ./db folder, find a Dockerfile, and build a custom image from it.
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    command: sh -c "sleep 10 && node ./backend/app.js"
    container_name: backend
    env_file: .env
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - mysql

  web:
    build: ./web
    container_name: web
    env_file: .env
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - backend

volumes:
  db_data:
