version: "3.8"
networks:
  expense_network:
    driver: bridge

volumes:
  db_data:

services:
  mysql:
    build: ./db
    #Go to the ./db folder, find a Dockerfile, and build a custom image from it.
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - expense_network

  backend:
    build: ./backend
    command: sh -c "sleep 20 && node app.js"
    container_name: backend
    env_file: .env
    networks:
      - expense_network
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - mysql

  web:
    build: ./web
    container_name: web
    env_file: .env
    networks:
      - expense_network
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - backend
