events {}

events {}

pid /tmp/nginx.pid;

http {
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /api/ {
            proxy_pass http://backend:8080/;
        }
    }
}
#If you change: proxy_pass http://backend:8080/; 
#Then backend gets: /api/add instead of /add, which is not what we want.