events {}

pid /tmp/nginx.pid;

http {
    server {
        listen ${NGINX_PORT};

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /api/ {
            proxy_pass http://backend:${BACKEND_PORT}/;
        }
    }
}
#Nginx does NOT support env vars directly → we fix this in Dockerfile.