events {}

pid /tmp/nginx.pid;

http {
    server {
        listen ${NGINX_PORT};
        # this block serves static files from the /usr/share/nginx/html directory.
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
       # This block handles API calls and proxies them to the backend service.
        location /api/ {
            proxy_pass http://backend:${BACKEND_PORT}/;
        }
    }
}
#Nginx does NOT support env vars directly → we fix this in Dockerfile.

#If you change: proxy_pass http://backend:${BACKEND_PORT};
#Then backend gets: /api/add instead of /add, which is not what we want.